#Auto generated by Edalize

TOP_MODULE        := nextpc_top
VC_FILE           := wlh_observations_nextpc_1.0.vc
VERILATOR_OPTIONS := -DDISABLE_PRIM_CDC_RAND_DELAY -Wall --unroll-count 72 -CFLAGS '-std=c++17 -Wall -Wextra -Werror'
MAKE_OPTIONS      := 
